model:
  base_learning_rate: 2.0e-06
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss
    
    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: 
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: 
      - 16
      dropout: 0.0
      tanh_out: false
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 16
    wrap: false
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: data/celebahqtrain.txt
        size: 256
        flip_p: 0.5
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: data/celebahqvalidation.txt
        size: 256
        flip_p: 0.5